name: ht_preferences_firestore
description: ...
repository: https://github.com/headlines-toolkit/ht-preferences-firestore
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.6
  flutter:
    sdk: flutter
  ht_preferences_client:
    git:
      url: https://github.com/headlines-toolkit/ht-preferences-client.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
